---
# A simple playbook to deploy LAMP server
# This example is using a single playbook

- hosts: servers

  vars:
    httpd_port: 80
    ntpserver: pool.ntp.org
    # Web repository
    repository: https://github.com/bennojoy/mywebapp.git

  tasks:
  - name: Install common dependencies
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
      - libselinux-python
      - libsemanage-python
      - firewalld

  - name: Install ntp
    yum:
      name: ntp
      state: present
    tags: ntp

  # NTP will only be restarted if config file is changed
  - name: Configure ntp file
    template:
      src: template/ntp.conf.j2
      dest: /etc/ntp.conf
    tags: ntp
    notify: restart ntp

  - name: Start the ntp service
    service:
      name: ntpd
      state: started
      enabled: yes
    tags: ntp

  - name: Install httpd and php
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
     - httpd
     - php
     - php-mysql

  - name: Install web role specific dependencies
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
     - git

  - name: Start firewalld
    service:
      name: firewalld
      state: started
      enabled: yes

  - name: Insert firewalld rule for httpd
    firewalld:
      port: "{{ httpd_port }}/tcp"
      permanent: true
      state: enabled
      immediate: yes

  - name: http service state
    service:
      name: httpd
      state: started
      enabled: yes

  - name: Configure SELinux to allow httpd to connect to remote database
    seboolean:
      name: httpd_can_network_connect_db
      state: true
      persistent: yes

  - name: Copy the web source code from Git repository
    git:
      repo: "{{ repository }}"
      dest: /var/www/html/

  - name: Creates the index.php file
    template:
      src: template/index.php.j2
      dest: /var/www/html/index.php

  - name: Install MariaDB package
    yum:
      name: "{{ item }}"
      state: installed
    with_items:
     - mariadb-server
     - MySQL-python

  - name: Create Mysql configuration file
    template:
      src: template/my.cnf.j2
      dest: /etc/my.cnf
    notify: restart mariadb

  - name: Start MariaDB Service
    service:
      name: mariadb
      state: started
      enabled: yes

  - name: Start firewalld
    service:
      name: firewalld
      state: started
      enabled: yes

  - name: insert firewalld rule
    firewalld:
      port: "{{ mysql_port }}/tcp"
      permanent: true
      state: enabled
      immediate: yes

  - name: Create Application Database
    mysql_db:
      name: "{{ dbname }}"
      state: present

  - name: Create Application DB User
    mysql_user:
      name: "{{ dbuser }}"
      password: "{{ upassword }}"
      priv: '*.*:ALL'
      host: '%%'
      state: present

  handlers:
    - name: restart ntp
      service:
        name: ntpd
        state: restarted

    - name: restart mariadb
      service:
        name: mariadb
        state: restarted
...
